name: Docker Image For Development
on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: briankim913/11-ellu-ai-summary-service
  VERSION: latest

jobs:
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .
      
      - name: Anchore Container Scan
        uses: anchore/scan-action@v6.2.0
        id: scan
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          fail-build: false
          severity-cutoff: high
          output-format: sarif
      
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3 
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      
      - name: Log into container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
